{% set version = "0.5.0" %}

package:
  name: ipywebrtc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywebrtc/ipywebrtc-{{ version }}.tar.gz
  sha256: 4db2be7d0bfcbd142b2f9f9e8303b926832a632ed4a3bc5681b319a5f226285a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - ipywidgets >=7.4

test:
  imports:
    - ipywebrtc

about:
  home: https://github.com/maartenbreddels/ipywebrtc
  license: MIT
  license_file: LICENSE
  summary: 'WebRTC for Jupyter notebook/lab'
  doc_url: https://ipywebrtc.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipywebrtc

extra:
  recipe-maintainers:
    - maartenbreddels
    - martinRenou
